# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
    dim_inactive = true  
    dim_strength = 0
    active_opacity = 0.98 
    inactive_opacity = 0.999
    fullscreen_opacity = 0.95
    blur {
        enabled = true
        size = 0
        passes = 0
        brightness = 1
        noise = 0
        contrast = 1
    }
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
